name: Release Please

on:
  push:
    branches:
      - main
      - 'hotfix/**'

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          release-type: simple
          package-name: test-commit
          draft-pull-request: "true"
          labels: "be-autorelease-pending"
          release-labels: "be-autorelease-tagged"
          target-branch: ${{ github.ref_name }}
          changelog-types: '[
            {"type":"feat","section":"Features","hidden":false},
            {"type":"feature","section":"Features","hidden":false},
            {"type":"fix","section":"Bugfix","hidden":false},
            {"type":"docs","section":"Documentation","hidden":false},
            {"type":"refactor","section":"Refactor","hidden":false},
            {"type":"ci","section":"CI","hidden":false},
            {"type":"perf","section":"Performance","hidden":false},
            {"type":"test","section":"Test","hidden":false},
            {"type":"build","section":"CI","hidden":false},
            {"type":"config","section":"Config","hidden":false},
            {"type":"infra","section":"Config","hidden":false},
            {"type":"chore","section":"Chore","hidden":false}
          ]'